# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.9.5"

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask
